### ISSUE TITLE
Add trailing slashes to links in footer

### ISSUE THREAD

**Issue by gosko** [w3c/w3c-website#131]
Many of the links in the footer on the [beta site](https://beta.w3.org/) should have trailing slashes, to avoid unnecessary redirects. I think the place to update this is [w3c_website_templates_bundle+intl-icu.en.yaml](https://github.com/w3c/w3c-website-templates-bundle/blob/main/translations/w3c_website_templates_bundle%2Bintl-icu.en.yaml)

Also I noticed a strange thing in the links in the other files in that directory: they all use /ja as the language prefix while they should be using /ar, /de, /es, /fr, ...

```
 links:
        home: __footer.links.home
        homeurl: /ja/
        contact: __footer.links.contact
        contacturl: /ja/contact
        help: __footer.links.help
        helpurl: /ja/help
        ...
```

should be:

```
 links:
        home: __footer.links.home
        homeurl: /ar/
        contact: __footer.links.contact
        contacturl: /ar/contact/
        help: __footer.links.help
        helpurl: /ar/help/
        ...
```
