### ISSUE TITLE
Description elements of a definition list are not indented 

### ISSUE THREAD

**Issue by lcarcone** [w3c/w3c-website#186]
_(Links updated to point to www.w3.org)_

We have a lot of legacy content with definition lists, like https://www.w3.org/events/talks/2000/talks/ for example, and the description elements (`<dd>`) are not indented (it is the default display in most browsers).
Margins are set to `0` in `core.css` (see below) and `margin-left` is not changed after.

```css
/*------------------------------------*\
    #Box sizing
\*------------------------------------*/
*,
*::before,
*::after {
  box-sizing: border-box;
  font-family: inherit;
  margin: 0;
  overflow-wrap: break-word;
  padding: 0;
}
```
