### ISSUE TITLE
AC Reps List is too widely spaced, company links too aggressive

### ISSUE THREAD

**Issue by fantasai** [w3c/w3c-website#459]
**Describe the issue**
If you load the list of AC reps, there is so much white space, and the text is so huge, it's hard to skim through the list. Additionally the company website link overtakes so much of the card entry, it's hard to interact with any of the other information. (For example, selecting an email address for copy/paste is very fiddly.)

**URL**
https://www.w3.org/Member/ACList

**Recommended solution**
Use spacing and font sizes appropriate for documents, not for iPad applications.

**Additional context**
The exaggerated font sizes and spacing are making the website harder to read and interact with in a lot of other places, too.

**Comment by japuiglaucia** [comment]
AC Reps List is too widely spaced, company links too aggressive #459

**Comment by frivoal** [comment]
I agree.

* The fact that the whole card of each AC Rep is a giant link to their company's website is aggravating. Visiting that side is very unlikely to be the most commonly desired interaction. Copying the email address ranks much higher, but it is made hard by the whole card being a clickable link.

* Another important use case for this page is skimming it, to find people you know. The excessive amount of spacing makes that impractical.

**Comment by vivienlacourba** [comment]
> * The fact that the whole card of each AC Rep is a giant link to their company's website is aggravating. Visiting that side is very unlikely to be the most commonly desired interaction. Copying the email address ranks much higher, but it is made hard by the whole card being a clickable link.

The "whole card is clickable" issue was also brought in #535.

**Comment by NicolaSaunders** [comment]
@vivienlacourba The example URL - https://www.w3.org/Member/ACList - requires being logged in and having certain permissions to be able to see it. I tried logging in with my credentials but was unable to access the page. Is it possible to allow me to see it, or for somebody to provide a screengrab indicating the issues? Thank you!

**Comment by vivienlacourba** [comment]
> @vivienlacourba The example URL - https://www.w3.org/Member/ACList - requires being logged in and having certain permissions to be able to see it. I tried logging in with my credentials but was unable to access the page. Is it possible to allow me to see it, or for somebody to provide a screengrab indicating the issues? Thank you!

@NicolaSaunders you should now have access to this page.

**Comment by frivoal** [comment]
In case it's useful to anyone else, I'm using the following user style sheet, to make the various people directory pages of the website a bit more tolerable (I apply it using the https://addons.mozilla.org/en-US/firefox/addon/styl-us/ Firefox extension).
```css
.card--user {
    padding: 5px 0 0 !important;
}
.card--user .not-sidebar * {
    margin-top: 0 !important;
    margin-bottom: 0 !important;
}
.card--user .not-sidebar .with-icon--before {
    padding: 0 !important;
}
.avatar {
    height: 3.5rem;
    width: 3.5rem;
    border: none;
}
.avatar img {
    transition-property: margin, width, height;
    transition-duration: 0.2s;
    height: 3.5rem !important;
    width: 3.5rem !important;
    border-radius: 50%;
    border: 1px solid;
    margin: 0;
    position: absolute;
}
.avatar:hover img {
    height: 8rem !important;
    width: 8rem !important;
    position: absolute;
    margin: -2rem;
    z-index: 1
}
.people-list {
    margin-bottom: 5px!important;
}
.txt-venus {
    margin-bottom: 2px!important;
    font-size: 1.6em;
    line-height: 1.2;
}
.l-sidebar.card--user {
    padding: 2px 0 !important;
}
.not-sidebar.card__text {
    margin: 2px!important;
}
.l-sidebar.card.card--member {
    margin-top: 5px !important;
    padding: 0.6rem
}
.member-list .card__text > * {
    max-width: none;
}
.txt-mars {
    font-size: 1.2em;
}
#main .component + .component {
    margin-top: 2.5rem;
}
```
On my screen, it makes the typical listing go from around 2 people per screen to about 6. It's quick and dirty, and I didn't give that much though to making it pretty, but for me, it brings the pages into usable range. With a bit more work, I'm sure it can be made both denser and prettier, but that's what I have.
