### ISSUE TITLE
list-no-bullets class no longer suppresses bullets

### ISSUE THREAD

**Issue by gosko** [w3c/w3c-website#679]
I think a recent change caused `class=list-no-bullets` to stop working, for example in the [Leadership section of a WG page](https://www.w3.org/groups/wg/ag/):

<img width="800" alt="Screenshot showing the issue" src="https://github.com/user-attachments/assets/db8f15ce-7c58-4f55-b6f1-e53729c6eab8">

In the past I believe these bullets were hidden due to these rules in core.css:

```css
ol[class],
ul[class] {
  list-style:none;
  padding:0
}
```
