### ISSUE TITLE
Technical reports and Global header pages - h1 text too large

### ISSUE THREAD

**Issue by gosko** [w3c/w3c-website#7]
The font size of the h1 on the [Technical reports page v2](https://w3c-dev.studio24.dev/technical-reports-v2/index.html) is quite large, causing this very short headline to be wrapped to two lines on desktop. This text feels way too big to me, and I can't find many other sites that use text that large (3.75rem)

Sample screenshot using Firefox on OS X:
![Screen Shot 2021-07-13 at 7 14 53 PM](https://user-images.githubusercontent.com/7144396/125550007-5e3d755e-d78f-42cd-b64b-2e9781e2b973.png)

Can we please consider reducing that font size? (and scaling others down as appropriate)

Same feedback for the [Global header](https://w3c-dev.studio24.dev/header-signedin/index.html) pages.

**Comment by JuliaSang** [comment]
Thank you for the feedback. As [noted on basecamp](https://3.basecamp.com/3091560/buckets/15695452/messages/3943802341#__recording_3961078358) we have not completed a styling review of this page yet, but we will do so once we've got in feedback on the rest of the page functionality. I'll keep this issue on hold until then.

**Comment by vivienlacourba** [comment]
In addition to those headers being too big I noticed that the h1 sizes were also different depending on the page template.

On pages with the `default` or `homepage` template the h1 `font-size` is `2.65rem` whereas on pages with the `listing`, `landing` or `ecosystem` templates it is `3.75rem`. And their `line-height` are also different.

I'm not sure if this is a bug or the desired behavior but having different heading sizes between those 3 templates seems strange to me.

Example of a page using the `default` template:
https://www-dev.w3.org/standards/about-w3c-standards/
```css
# core.css:1795 @screen and (min-width: 48em)
h1, .txt-venus {
	font-size: 2.625rem;
	line-height: calc(58.8 / 42);
}
```

Example of a page using the `landing` template:
https://www-dev.w3.org/standards/
```css
# core.css:4169 @screen and (min-width: 48em)
.landing h1, .ecosystem h1 {
	font-size: 3.75rem;
	line-height: calc(72 / 60);
}
```

Vivien
